# Use the official .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the project files and restore dependencies
COPY API/API.csproj ./
RUN dotnet restore

# Copy the remaining files and build the application
COPY API/ ./
RUN mv docker.appsettings.json appsettings.json
RUN dotnet publish 'API.csproj' -c Release -o /app/publish/api

# Use the official .NET runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish/api .

# Expose the port the application runs on
EXPOSE 8080

# Specify the entry point for the application
ENTRYPOINT ["dotnet", "API.dll"]
